apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
      - name: app-backend
        image: alejandravillalobos/expenses-backend:0.1.0
        env:
        - name: SERVER_PORT
          value: "8500"
        - name: ORACLE_USER
          value: "appuser"
        - name: ORACLE_PASSWORD
          value: "mypasswordapp"
        - name: ORACLE_CONNSTR
          value: "service-oracle:1521/xepdb1" 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: service-backend
spec:
  type: LoadBalancer
  selector:
    app: app-backend
  ports:
  - port: 8500
    targetPort: 8500