apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-cm
data:
  init.sql: |
    ALTER SESSION SET CONTAINER=XEPDB1;

    CREATE TABLE APPUSER.PERSON (
      PERSON NUMBER,
      NAME VARCHAR2(100) NOT NULL,
      EMAIL VARCHAR2(100) NOT NULL,
      PASSWORD VARCHAR2(100) NOT NULL,
      PRIMARY KEY(PERSON)
    );

    CREATE SEQUENCE APPUSER.SQ_PERSON NOCACHE;

    CREATE TABLE APPUSER.BANK (
      ID NUMBER,
      ACCOUNT VARCHAR2(15) NOT NULL,
      NAME VARCHAR2(50) NOT NULL,
      CURRENCY VARCHAR2(10) NOT NULL,
      AMOUNT FLOAT NOT NULL,
      PERSON NUMBER NOT NULL,
      USER_NAME VARCHAR(100) NOT NULL,
      PRIMARY KEY (ID),
      FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON)
    );

    CREATE SEQUENCE APPUSER.SQ_BANK NOCACHE;

    CREATE TABLE APPUSER.INCOME (
      ID NUMBER,
      CATEGORY VARCHAR2(10) NOT NULL,
      DESCRIPTION VARCHAR2(50),
      AMOUNT FLOAT NOT NULL,
      ADD_DATE DATE DEFAULT SYSDATE,
      BANK NUMBER NOT NULL,
      PERSON NUMBER NOT NULL,
      FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON),
      PRIMARY KEY (ID),
      FOREIGN KEY(BANK) REFERENCES APPUSER.BANK(ID)
    );

    CREATE SEQUENCE APPUSER.SQ_INCOME NOCACHE;

    CREATE TABLE APPUSER.OUTCOME (
      ID NUMBER,
      CATEGORY VARCHAR2(10) NOT NULL,
      DESCRIPTION VARCHAR2(50),
      AMOUNT FLOAT NOT NULL,
      ADD_DATE DATE DEFAULT SYSDATE,
      TO_ACCOUNT VARCHAR2(15),
      TO_BANK VARCHAR2(50),
      BANK NUMBER NOT NULL,
      PERSON NUMBER NOT NULL,
      FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON),
      PRIMARY KEY (ID),
      FOREIGN KEY(BANK) REFERENCES APPUSER.BANK(ID)
    );

    CREATE SEQUENCE APPUSER.SQ_OUTCOME NOCACHE;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-oracle-pv-claim
  labels:
    app: db-oracle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-oracle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-oracle
  template:
    metadata:
      labels:
        app: db-oracle
    spec:
      securityContext:
        runAsUser: 54321    # Oracle User 
        runAsGroup: 54321   # Oinstall group
        fsGroup: 54321      # Oinstall group
      volumes:
      - name: db-init-volume
        configMap:
          name: db-init-cm
      - name: db-oracle-persistent-storage
        persistentVolumeClaim:
          claimName: db-oracle-pv-claim
      containers:
      - name: db-oracle
        image: gvenzl/oracle-xe
        env:
        - name: ORACLE_PASSWORD
          value: "mypassword"
        - name: APP_USER
          value: "appuser"
        - name: APP_USER_PASSWORD
          value: "mypasswordapp"
        resources:
          limits:
            memory: "3000Mi"
            cpu: "500m"
        ports:
        - containerPort: 1521
        volumeMounts:
        - name: db-init-volume
          mountPath: /container-entrypoint-initdb.d
        - name: db-oracle-persistent-storage
          mountPath: /opt/oracle/oradata
---
apiVersion: v1
kind: Service
metadata:
  name: service-oracle
spec:
  type: ClusterIP
  selector:
    app: db-oracle
  ports:
  - port: 1521
    targetPort: 1521