ALTER SESSION SET CONTAINER=XEPDB1;

CREATE TABLE APPUSER.PERSON (
	PERSON NUMBER,
	NAME VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL,
	PASSWORD VARCHAR2(100) NOT NULL,
	PRIMARY KEY(PERSON)
);

CREATE SEQUENCE APPUSER.SQ_PERSON NOCACHE;

CREATE TABLE APPUSER.BANK (
	ID NUMBER,
	ACCOUNT VARCHAR2(15) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	CURRENCY VARCHAR2(10) NOT NULL,
	AMOUNT FLOAT NOT NULL,
	PERSON NUMBER NOT NULL,
	USER_NAME VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON)
);

CREATE SEQUENCE APPUSER.SQ_BANK NOCACHE;

CREATE TABLE APPUSER.INCOME (
	ID NUMBER,
	CATEGORY VARCHAR2(10) NOT NULL,
	DESCRIPTION VARCHAR2(50),
	AMOUNT FLOAT NOT NULL,
	ADD_DATE DATE DEFAULT SYSDATE,
	BANK NUMBER NOT NULL,
	PERSON NUMBER NOT NULL,
	FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON),
	PRIMARY KEY (ID),
	FOREIGN KEY(BANK) REFERENCES APPUSER.BANK(ID)
);

CREATE SEQUENCE APPUSER.SQ_INCOME NOCACHE;

CREATE TABLE APPUSER.OUTCOME (
	ID NUMBER,
	CATEGORY VARCHAR2(10) NOT NULL,
	DESCRIPTION VARCHAR2(50),
	AMOUNT FLOAT NOT NULL,
	ADD_DATE DATE DEFAULT SYSDATE,
	TO_ACCOUNT VARCHAR2(15),
	TO_BANK VARCHAR2(50),
	BANK NUMBER NOT NULL,
	PERSON NUMBER NOT NULL,
	FOREIGN KEY(PERSON) REFERENCES APPUSER.PERSON(PERSON),
	PRIMARY KEY (ID),
	FOREIGN KEY(BANK) REFERENCES APPUSER.BANK(ID)
);

CREATE SEQUENCE APPUSER.SQ_OUTCOME NOCACHE;